version: '3'
services:

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    restart: always
    ports:
    - "8400:80"
    volumes:
    - /data:/data
    - /etc/timezone:/etc/timezone:ro
    environment:
      - NGINX_MAX_UPLOAD=750m
      - UWSGI_PROCESSES=20
      - UWSGI_THREADS=2
      - FLASK_ENV=development
    depends_on:
      - cromwell
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]

  cromwell:
    build:
      context: .
      dockerfile: Dockerfile.cromwell
    restart: always
    environment:
      - JAVA_OPTS=-Ddocker.hash-lookup.enabled=false -Dsystem.max-concurrent-workflows=3 -Dbackend.providers.Local.config.root=/data/gwas2vcfweb/cromwell-executions -Dworkflow-options.workflow-log-dir=/data/gwas2vcfweb/cromwell-workflow-logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data:/data
      - /etc/timezone:/etc/timezone:ro
    command: ["server"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
